version: "0.1"
user: vishnurv2
key: 2dEK8rin7XC3cChRqccFoMlcC9FwPNloQdqV9c4y7vFUAnAB18
testSuites: []
pre: [npm install playwright@1.25.0 --save-exact, dotnet list PlaywrightDotnetTests.csproj
    package > packages.txt, nuget locals all -clear, dotnet build -c Release]
post: [cat Autosplit.yaml]
env:
  NUGET_HTTP_CACHE_PATH: C:\nuget_http_cache
  NUGET_PACKAGES: C:\nuget_global_cache
  NUGET_PLUGINS_CACHE_PATH: C:\nuget_plugins_cache
jobLabel:
- playwright
runson: win
autosplit: true
concurrency: 3
testDiscovery:
  command: grep "case" Program.cs | awk '{print$2}' | sed 's/://g'
  mode: static
  type: raw
testDiscoveryResult:
- '"single"'
- '"iphonetest"'
- '"ipadtest"'
testRunnerCommand: dotnet run $test
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
cacheKey: '{{ checksum "packages.txt" }}'
retryOnFailure: true
maxRetries: 5
jobID: 198a7a64-6e7c-467a-80b2-1956667c3e08
codeDirectory: playwright-csharp
runtime:
  language: dotnet
  version: 6.0.303
framework:
  name: ""
  flags: []
  discoveryType: ""
  workingDirectory: ""
  isTestNGXMLSuite: false
  defaultReports: true
cypress: false
betaFeature:
  setPartiallyCompletedAsCompleted: false
